package mta.th12a.tuanhiep.model;


// Generated Oct 10, 2016 7:18:39 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name="BRANDS"
    ,schema="dbo"
    ,catalog="LTNC_THOITRANG"
)
public class Brands  implements java.io.Serializable {


     private int brandId;
     private String brandName;
     private Boolean isActive;

    public Brands() {
    }

	
    public Brands(int brandId) {
        this.brandId = brandId;
    }
    public Brands(int brandId, String brandName, Boolean isActive) {
       this.brandId = brandId;
       this.brandName = brandName;
       this.isActive = isActive;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.AUTO) //for autonumber
    @Column(name="Brand_ID", unique=true, nullable=false)
    public int getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(int brandId) {
        this.brandId = brandId;
    }

    
    @Column(name="Brand_Name", length=200)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


