package mta.th12a.tuanhiep.model;
// Generated Oct 10, 2016 7:18:39 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="ORDERS"
    ,schema="dbo"
    ,catalog="LTNC_THOITRANG"
)
public class Orders  implements java.io.Serializable {


     private int orderId;
     private Integer customerId;
     private String customerName;
     private String customerAddress;
     private String customerPhone;
     private String customerEmail;
     private Integer status;
     private Boolean isActive;

    public Orders() {
    }

	
    public Orders(int orderId) {
        this.orderId = orderId;
    }
    public Orders(int orderId, Integer customerId, String customerName, String customerAddress, String customerPhone, String customerEmail, Integer status, Boolean isActive) {
       this.orderId = orderId;
       this.customerId = customerId;
       this.customerName = customerName;
       this.customerAddress = customerAddress;
       this.customerPhone = customerPhone;
       this.customerEmail = customerEmail;
       this.status = status;
       this.isActive = isActive;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.AUTO) //for autonumber
    @Column(name="Order_ID", unique=true, nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    
    @Column(name="Customer_ID")
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Customer_Name", length=200)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="Customer_Address", length=200)
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    
    @Column(name="Customer_Phone", length=200)
    public String getCustomerPhone() {
        return this.customerPhone;
    }
    
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    
    @Column(name="Customer_Email", length=200)
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    
    @Column(name="Status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


