package mta.th12a.tuanhiep.model;
// Generated Oct 10, 2016 7:18:39 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="ORDER_DETAILS"
    ,schema="dbo"
    ,catalog="LTNC_THOITRANG"
)
public class OrderDetails  implements java.io.Serializable {


     private int orderDetailId;
     private Integer productStoreId;
     private Integer orderId;
     private Integer orderDetailQuantity;
     private String note;
     private Boolean isActive;

    public OrderDetails() {
    }

	
    public OrderDetails(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public OrderDetails(int orderDetailId, Integer productStoreId,Integer orderId, Integer orderDetailQuantity, String note, Boolean isActive) {
       this.orderDetailId = orderDetailId;
       this.orderId=orderId;
       this.productStoreId = productStoreId;
       this.orderDetailQuantity = orderDetailQuantity;
       this.note = note;
       this.isActive = isActive;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.AUTO) //for autonumber
    @Column(name="Order_Detail_ID", unique=true, nullable=false)
    public int getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    
    @Column(name="Order_ID")
    public Integer getOrderId() {
		return orderId;
	}


	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}


	@Column(name="Product_Store_ID")
    public Integer getProductStoreId() {
        return this.productStoreId;
    }
    
    public void setProductStoreId(Integer productStoreId) {
        this.productStoreId = productStoreId;
    }

    
    @Column(name="Order_Detail_Quantity")
    public Integer getOrderDetailQuantity() {
        return this.orderDetailQuantity;
    }
    
    public void setOrderDetailQuantity(Integer orderDetailQuantity) {
        this.orderDetailQuantity = orderDetailQuantity;
    }

    
    @Column(name="Note", length=200)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


