package mta.th12a.tuanhiep.model;
// Generated Oct 10, 2016 7:18:39 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductImages generated by hbm2java
 */
@Entity
@Table(name="PRODUCT_IMAGES"
    ,schema="dbo"
    ,catalog="LTNC_THOITRANG"
)
public class ProductImages  implements java.io.Serializable {

	
     private int productImageId;
     private String productImageUrl;
     private String productImageName;
     private Boolean isActive;

    public ProductImages() {
    }

	
    public ProductImages(int productImageId) {
        this.productImageId = productImageId;
    }
    public ProductImages(int productImageId, String productImageUrl, String productImageName, Boolean isActive) {
       this.productImageId = productImageId;
       this.productImageUrl = productImageUrl;
       this.productImageName = productImageName;
       this.isActive = isActive;
    }
   
     @Id 

     @GeneratedValue(strategy=GenerationType.AUTO) //for autonumber
    @Column(name="Product_Image_ID", unique=true, nullable=false)
    public int getProductImageId() {
        return this.productImageId;
    }
    
    public void setProductImageId(int productImageId) {
        this.productImageId = productImageId;
    }

    
    @Column(name="Product_Image_Url", length=200)
    public String getProductImageUrl() {
        return this.productImageUrl;
    }
    
    public void setProductImageUrl(String productImageUrl) {
        this.productImageUrl = productImageUrl;
    }

    
    @Column(name="Product_Image_Name", length=200)
    public String getProductImageName() {
        return this.productImageName;
    }
    
    public void setProductImageName(String productImageName) {
        this.productImageName = productImageName;
    }

    
    @Column(name="IsActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


