package mta.th12a.tuanhiep.model;
// Generated Oct 10, 2016 7:18:39 PM by Hibernate Tools 4.3.1



import javax.persistence.Entity;
import javax.persistence.MappedSuperclass;
import javax.persistence.Table;

/**
 * ProductStores generated by hbm2java
 */
@Entity
@MappedSuperclass
@Table(name="PRODUCT_STORES"
    ,schema="dbo"
    ,catalog="LTNC_THOITRANG"
)
public class ProductStores  extends ProductStoresObjec{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

}


